name: Publish the website

on:
  create:
    tags:
      - "*"

jobs:
  publish:
    name: Publish javadoc
    runs-on: ubuntu-latest
    steps:
      - name: Generate javadoc
        working-directory: site
        run: docker-compose run generate-javadoc
      - name: Publish javadoc to calcite-site repository
        working-directory: site
        run: echo Publishing...